on: [push]

jobs:
  msrv:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - uses: dtolnay/rust-toolchain@1.51.0
    - run: cargo check
    - run: cargo update --package once_cell --precise 1.14.0
    - run: cargo check --features "json encoding_rs flate2"
