on: [push]

jobs:
  msrv:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: 1.51.0
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: update
        args: --package once_cell --precise 1.14.0
    - uses: actions-rs/cargo@v1
      with:
        command: check
        args: --all-features
